const plugin = require('tailwindcss/plugin');

module.exports = plugin(function({ addBase, addComponents, theme }) {
  addBase({
    /* Default Theme (Slate) */
    ':root': {
      '--alt-bg': '#f1f5f9',
      '--alt-fg': '#0f172a',
      '--alt-muted': '#e2e8f0',
      '--alt-border': '#cbd5e1',
      '--alt-primary': '#475569',
      '--alt-radius': '0.5rem',
      '--alt-ring': 'rgba(71,85,105,0.15)',
      '--alt-shadow': '0 4px 6px -1px rgba(0,0,0,0.05)',
    },
    '[data-theme="ivory"]': {
      '--alt-bg': '#fcfcf9',
      '--alt-fg': '#1a1a1a',
      '--alt-muted': '#f3f3ee',
      '--alt-border': '#e6e6e0',
      '--alt-primary': '#5c5c5c',
      '--alt-ring': 'rgba(0,0,0,0.1)',
      '--alt-shadow': '0 4px 12px rgba(0,0,0,0.05)',
    },
    '[data-theme="mocha"]': {
      '--alt-bg': '#1c1917',
      '--alt-fg': '#fafaf9',
      '--alt-muted': '#292524',
      '--alt-border': '#44403c',
      '--alt-primary': '#d6d3d1',
      '--alt-ring': 'rgba(214,211,209,0.1)',
      '--alt-shadow': '0 10px 25px -5px rgba(0,0,0,0.4)',
    },
    '[data-theme="navy"]': {
      '--alt-bg': '#0f172a',
      '--alt-fg': '#f8fafc',
      '--alt-muted': '#1e293b',
      '--alt-border': '#334155',
      '--alt-primary': '#38bdf8',
      '--alt-ring': 'rgba(56,189,248,0.2)',
      '--alt-shadow': '0 10px 25px -5px rgba(0,0,0,0.3)',
    },
    '[data-theme="obsidian"]': {
      '--alt-bg': '#000000',
      '--alt-fg': '#ffffff',
      '--alt-muted': '#111111',
      '--alt-border': '#222222',
      '--alt-primary': '#ffffff',
      '--alt-ring': 'rgba(255,255,255,0.1)',
      '--alt-shadow': '0 8px 30px rgba(0,0,0,0.5)',
    },
    'body': {
      'backgroundColor': 'var(--alt-bg)',
      'color': 'var(--alt-fg)',
      'fontFamily': 'Inter, system-ui, -apple-system, sans-serif',
      'transition': 'background-color 0.3s ease, color 0.3s ease',
    }
  });

  addComponents({
    '.btn-altus': {
      'display': 'inline-flex',
      'alignItems': 'center',
      'justifyContent': 'center',
      'padding': '0.75rem 1.5rem',
      'fontSize': '0.875rem',
      'fontWeight': '600',
      'borderRadius': 'var(--alt-radius)',
      'backgroundColor': 'var(--alt-fg)',
      'color': 'var(--alt-bg)',
      'boxShadow': 'var(--alt-shadow)',
      'transition': 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
      'cursor': 'pointer',
      'border': '1px solid transparent',
      '&:hover': {
        'opacity': '0.9',
        'transform': 'translateY(-1px)',
        'boxShadow': '0 10px 15px -3px var(--alt-ring)',
      },
      '&:active': {
        'transform': 'translateY(0)',
      }
    },
    '.btn-altus-outline': {
      'display': 'inline-flex',
      'alignItems': 'center',
      'justifyContent': 'center',
      'padding': '0.75rem 1.5rem',
      'fontSize': '0.875rem',
      'fontWeight': '600',
      'borderRadius': 'var(--alt-radius)',
      'backgroundColor': 'transparent',
      'color': 'var(--alt-fg)',
      'border': '1px solid var(--alt-border)',
      'transition': 'all 0.2s ease',
      '&:hover': {
        'backgroundColor': 'var(--alt-muted)',
        'borderColor': 'var(--alt-primary)',
      }
    },
    '.btn-altus-ghost': {
      'display': 'inline-flex',
      'alignItems': 'center',
      'justifyContent': 'center',
      'padding': '0.75rem 1.5rem',
      'fontSize': '0.875rem',
      'fontWeight': '600',
      'borderRadius': 'var(--alt-radius)',
      'backgroundColor': 'transparent',
      'color': 'var(--alt-fg)',
      'transition': 'all 0.2s ease',
      'cursor': 'pointer',
      'border': '1px solid transparent',
      '&:hover': {
        'backgroundColor': 'var(--alt-muted)',
        'color': 'var(--alt-primary)',
      }
    },
    '.btn-altus-icon': {
      'display': 'inline-flex',
      'alignItems': 'center',
      'justifyContent': 'center',
      'width': '2.5rem',
      'height': '2.5rem',
      'borderRadius': 'var(--alt-radius)',
      'backgroundColor': 'transparent',
      'color': 'var(--alt-fg)',
      'border': '1px solid var(--alt-border)',
      'transition': 'all 0.2s ease',
      'cursor': 'pointer',
      '&:hover': {
        'backgroundColor': 'var(--alt-muted)',
        'borderColor': 'var(--alt-primary)',
      }
    },
    '.btn-altus-fab': {
      'display': 'inline-flex',
      'alignItems': 'center',
      'justifyContent': 'center',
      'width': '3.5rem',
      'height': '3.5rem',
      'borderRadius': '9999px',
      'backgroundColor': 'var(--alt-fg)',
      'color': 'var(--alt-bg)',
      'boxShadow': '0 10px 25px -5px var(--alt-ring)',
      'transition': 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      'cursor': 'pointer',
      'border': 'none',
      '&:hover': {
        'transform': 'scale(1.05) translateY(-2px)',
        'boxShadow': '0 20px 30px -5px var(--alt-ring)',
      },
      '&:active': {
        'transform': 'scale(0.95)',
      }
    },
    '.altus-card': {
      'backgroundColor': 'var(--alt-bg)',
      'border': '1px solid var(--alt-border)',
      'borderRadius': 'var(--alt-radius)',
      'boxShadow': 'var(--alt-shadow)',
      'padding': '1.5rem',
      'transition': 'transform 0.2s ease, box-shadow 0.2s ease',
      '&:hover': {
        'boxShadow': '0 20px 25px -5px var(--alt-ring)',
      }
    },
    '.altus-input': {
      'width': '100%',
      'padding': '0.75rem 1.25rem',
      'fontSize': '0.875rem',
      'backgroundColor': 'var(--alt-bg)',
      'color': 'var(--alt-fg)',
      'border': '1px solid var(--alt-border)',
      'borderRadius': 'var(--alt-radius)',
      'transition': 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      'outline': 'none',
      'boxShadow': 'inset 0 1px 2px rgba(0,0,0,0.02)',
      '&::placeholder': {
        'color': 'var(--alt-fg)',
        'opacity': '0.3',
      },
      '&:hover': {
        'borderColor': 'var(--alt-primary)',
        'backgroundColor': 'var(--alt-muted)',
      },
      '&:focus': {
        'borderColor': 'var(--alt-primary)',
        'backgroundColor': 'var(--alt-bg)',
        'boxShadow': '0 0 0 4px var(--alt-ring), inset 0 1px 2px rgba(0,0,0,0.02)',
      }
    },
    '.altus-select': {
      'appearance': 'none',
      'width': '100%',
      'padding': '0.75rem 2.5rem 0.75rem 1.25rem',
      'fontSize': '0.875rem',
      'backgroundColor': 'var(--alt-bg)',
      'color': 'var(--alt-fg)',
      'border': '1px solid var(--alt-border)',
      'borderRadius': 'var(--alt-radius)',
      'cursor': 'pointer',
      'backgroundImage': 'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' fill=\'none\' viewBox=\'0 0 24 24\' stroke=\'currentColor\'%3E%3Cpath stroke-linecap=\'round\' stroke-linejoin=\'round\' stroke-width=\'2\' d=\'M19 9l-7 7-7-7\' /%3E%3C/svg%3E")',
      'backgroundRepeat': 'no-repeat',
      'backgroundPosition': 'right 1rem center',
      'backgroundSize': '1rem',
      'transition': 'all 0.2s ease',
      '&:focus': {
        'borderColor': 'var(--alt-primary)',
        'boxShadow': '0 0 0 4px var(--alt-ring)',
        'outline': 'none',
      }
    },
    '.altus-badge': {
      'display': 'inline-flex',
      'alignItems': 'center',
      'padding': '0.25rem 0.625rem',
      'fontSize': '10px',
      'fontWeight': '700',
      'textTransform': 'uppercase',
      'letterSpacing': '0.1em',
      'borderRadius': '9999px',
      'backgroundColor': 'var(--alt-muted)',
      'color': 'var(--alt-fg)',
      'border': '1px solid var(--alt-border)',
    },
    '.altus-skeleton': {
      'backgroundColor': 'var(--alt-muted)',
      'borderRadius': 'var(--alt-radius)',
      'position': 'relative',
      'overflow': 'hidden',
      '&::after': {
        'content': '""',
        'position': 'absolute',
        'inset': '0',
        'transform': 'translateX(-100%)',
        'backgroundImage': 'linear-gradient(90deg, transparent, rgba(255,255,255,0.05), transparent)',
        'animation': 'altus-shimmer 2s infinite',
      }
    },
    '.altus-spinner': {
      'width': '1.5rem',
      'height': '1.5rem',
      'border': '2px solid var(--alt-muted)',
      'borderTopColor': 'var(--alt-primary)',
      'borderRadius': '50%',
      'animation': 'altus-spin 0.8s linear infinite',
    },
    '@keyframes altus-shimmer': {
      '100%': { 'transform': 'translateX(100%)' },
    },
    '@keyframes altus-spin': {
      'to': { 'transform': 'rotate(360deg)' },
    },
    '.altus-checkbox': {
      'appearance': 'none',
      'width': '1.25rem',
      'height': '1.25rem',
      'border': '2px solid var(--alt-border)',
      'borderRadius': '0.375rem',
      'backgroundColor': 'var(--alt-bg)',
      'cursor': 'pointer',
      'position': 'relative',
      'transition': 'all 0.2s ease',
      '&:hover': {
        'borderColor': 'var(--alt-primary)',
      },
      '&:checked': {
        'backgroundColor': 'var(--alt-primary)',
        'borderColor': 'var(--alt-primary)',
      },
      '&:checked::after': {
        'content': '""',
        'position': 'absolute',
        'left': '50%',
        'top': '50%',
        'transform': 'translate(-50%, -50%)',
        'width': '6px',
        'height': '6px',
        'borderRadius': '50%',
        'backgroundColor': 'var(--alt-bg)',
      },
      '&:focus': {
        'boxShadow': '0 0 0 4px var(--alt-ring)',
      }
    },
    '.altus-switch': {
      'appearance': 'none',
      'width': '2.75rem',
      'height': '1.5rem',
      'backgroundColor': 'var(--alt-muted)',
      'borderRadius': '2rem',
      'position': 'relative',
      'cursor': 'pointer',
      'transition': 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
      'border': '1px solid var(--alt-border)',
      '&::before': {
        'content': '""',
        'position': 'absolute',
        'width': '1.125rem',
        'height': '1.125rem',
        'backgroundColor': 'var(--alt-fg)',
        'borderRadius': '50%',
        'top': '2px',
        'left': '2px',
        'transition': 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
        'boxShadow': '0 1px 3px rgba(0,0,0,0.1)',
      },
      '&:checked': {
        'backgroundColor': 'var(--alt-primary)',
        'borderColor': 'var(--alt-primary)',
      },
      '&:checked::before': {
        'left': 'calc(2.75rem - 1.25rem - 1px)',
        'backgroundColor': 'var(--alt-bg)',
        'transform': 'scale(1.1)',
      }
    },
    '.altus-label': {
      'display': 'block',
      'fontSize': '0.75rem',
      'fontWeight': '700',
      'textTransform': 'uppercase',
      'letterSpacing': '0.1em',
      'marginBottom': '0.5rem',
      'color': 'var(--alt-fg)',
      'opacity': '0.8',
    },
    '.altus-divider': {
      'width': '100%',
      'height': '1px',
      'backgroundColor': 'var(--alt-border)',
      'position': 'relative',
      'margin': '2rem 0',
      '&::before': {
        'content': '""',
        'position': 'absolute',
        'left': '0',
        'top': '-2px',
        'width': '5px',
        'height': '5px',
        'borderRadius': '50%',
        'backgroundColor': 'var(--alt-primary)',
      }
    },
    '.altus-accordion': {
      'border': '1px solid var(--alt-border)',
      'borderRadius': 'var(--alt-radius)',
      'backgroundColor': 'var(--alt-bg)',
      'overflow': 'hidden',
    },
    '.altus-accordion-item': {
      'borderBottom': '1px solid var(--alt-border)',
      '&:last-child': {
        'borderBottom': 'none',
      }
    },
    '.altus-accordion-trigger': {
      'width': '100%',
      'padding': '1rem 1.5rem',
      'display': 'flex',
      'alignItems': 'center',
      'justifyContent': 'space-between',
      'textAlign': 'left',
      'fontSize': '0.875rem',
      'fontWeight': '600',
      'backgroundColor': 'transparent',
      'color': 'var(--alt-fg)',
      'transition': 'all 0.2s ease',
      'cursor': 'pointer',
      '&:hover': {
        'backgroundColor': 'var(--alt-muted)',
      }
    },
    '.altus-accordion-content': {
      'padding': '0 1.5rem 1.5rem',
      'fontSize': '0.875rem',
      'color': 'var(--alt-fg)',
      'opacity': '0.7',
      'lineHeight': '1.6',
    },
    '.altus-tooltip': {
      'position': 'absolute',
      'zIndex': '50',
      'padding': '0.5rem 0.75rem',
      'fontSize': '10px',
      'fontWeight': '700',
      'textTransform': 'uppercase',
      'letterSpacing': '0.15em',
      'backgroundColor': 'var(--alt-fg)',
      'color': 'var(--alt-bg)',
      'borderRadius': '0.25rem',
      'boxShadow': 'var(--alt-shadow)',
      'pointerEvents': 'none',
      'whiteSpace': 'nowrap',
    },
    '.altus-overlay': {
      'position': 'fixed',
      'inset': '0',
      'backgroundColor': 'rgba(0,0,0,0.4)',
      'backdropFilter': 'blur(4px)',
      'zIndex': '100',
    },
    '.altus-modal': {
      'position': 'fixed',
      'top': '50%',
      'left': '50%',
      'transform': 'translate(-50%, -50%)',
      'zIndex': '110',
      'width': '90%',
      'maxWidth': '500px',
      'backgroundColor': 'var(--alt-bg)',
      'borderRadius': 'var(--alt-radius)',
      'border': '1px solid var(--alt-border)',
      'boxShadow': '0 25px 50px -12px rgba(0,0,0,0.25)',
      'padding': '2rem',
    },
    '.altus-toast': {
      'padding': '0.75rem 1rem',
      'backgroundColor': 'var(--alt-fg)',
      'color': 'var(--alt-bg)',
      'borderRadius': 'var(--alt-radius)',
      'boxShadow': 'var(--alt-shadow)',
      'fontSize': '0.875rem',
      'fontWeight': '600',
      'display': 'flex',
      'alignItems': 'center',
      'gap': '0.75rem',
      'pointerEvents': 'auto',
      'border': '1px solid var(--alt-border)',
      'minWidth': '300px',
      'maxWidth': 'calc(100vw - 2rem)',
      'position': 'relative',
      'overflow': 'hidden',
      '@media (max-width: 640px)': {
        'minWidth': 'calc(100vw - 3rem)',
      }
    },
    '.altus-toast-close': {
      'marginLeft': 'auto',
      'display': 'inline-flex',
      'alignItems': 'center',
      'justifyContent': 'center',
      'width': '1.5rem',
      'height': '1.5rem',
      'borderRadius': '0.25rem',
      'cursor': 'pointer',
      'opacity': '0.5',
      'transition': 'all 0.2s ease',
      'border': 'none',
      'backgroundColor': 'transparent',
      'color': 'inherit',
      '&:hover': {
        'opacity': '1',
        'backgroundColor': 'rgba(0,0,0,0.1)',
      }
    },
    '.altus-toast-success': {
      'backgroundColor': '#ecfdf5',
      'color': '#065f46',
      'borderColor': '#a7f3d0',
    },
    '.altus-toast-error': {
      'backgroundColor': '#fef2f2',
      'color': '#991b1b',
      'borderColor': '#fecaca',
    },
    '.altus-toast-info': {
      'backgroundColor': '#eff6ff',
      'color': '#1e40af',
      'borderColor': '#bfdbfe',
    },
    '.altus-toast-container': {
      'position': 'fixed',
      'zIndex': '250',
      'display': 'flex',
      'flexDirection': 'column',
      'gap': '0.5rem',
      'pointerEvents': 'none',
      'padding': '1rem',
      'width': '100%',
      'maxWidth': 'max-content',
      'alignItems': 'center',
      '@media (max-width: 640px)': {
        'left': '0 !important',
        'right': '0 !important',
        'width': '100% !important',
        'maxWidth': '100% !important',
        'transform': 'none !important',
        'padding': '1rem',
        'alignItems': 'center',
      }
    },
    '.altus-toast-container.top-center': {
      'top': '0',
      'left': '50%',
      'transform': 'translateX(-50%)',
    },
    '.altus-toast-container.bottom-center': {
      'bottom': '0',
      'left': '50%',
      'transform': 'translateX(-50%)',
    },
    '.altus-toast-container.bottom-right': {
      'bottom': '0',
      'right': '0',
      'alignItems': 'flex-end',
    },
    '.altus-nav-overlay': {
      'position': 'fixed',
      'inset': '0',
      'backgroundColor': 'var(--alt-bg)',
      'zIndex': '200',
      'padding': '6rem 2rem 2rem',
      'display': 'flex',
      'flexDirection': 'column',
    },
    '.altus-nav-link': {
      'fontSize': '2.5rem',
      'fontWeight': '900',
      'textTransform': 'uppercase',
      'letterSpacing': '-0.02em',
      'color': 'var(--alt-fg)',
      'transition': 'all 0.3s ease',
      'display': 'block',
      'borderBottom': '1px solid transparent',
      'width': 'fit-content',
      '&:hover': {
        'letterSpacing': '0.05em',
        'color': 'var(--alt-primary)',
      }
    },
    '.altus-logo': {
      'height': '1.5rem',
      'width': 'auto',
      'filter': 'none',
      'transition': 'filter 0.3s ease',
    },
    '[data-theme="navy"] .altus-logo, [data-theme="obsidian"] .altus-logo, [data-theme="mocha"] .altus-logo': {
      'filter': 'invert(1)',
    },
  });
}, {
  theme: {
    extend: {
      colors: {
        altus: {
          bg: 'var(--alt-bg)',
          fg: 'var(--alt-fg)',
          muted: 'var(--alt-muted)',
          border: 'var(--alt-border)',
          primary: 'var(--alt-primary)',
        }
      },
      borderRadius: {
        altus: 'var(--alt-radius)',
      }
    }
  }
});
