module.exports = {
  '.altus-accordion': {
    'border': '1px solid var(--alt-border)',
    'borderRadius': 'var(--alt-radius)',
    'backgroundColor': 'var(--alt-bg)',
    'overflow': 'hidden',
  },
  '.altus-accordion-item': {
    'borderBottom': '1px solid var(--alt-border)',
    '&:last-child': {
      'borderBottom': 'none',
    }
  },
  '.altus-accordion-trigger': {
    'width': '100%',
    'padding': '1rem 1.5rem',
    'display': 'flex',
    'alignItems': 'center',
    'justifyContent': 'space-between',
    'textAlign': 'left',
    'fontSize': '0.875rem',
    'fontWeight': '600',
    'backgroundColor': 'transparent',
    'color': 'var(--alt-fg)',
    'transition': 'all 0.2s ease',
    'cursor': 'pointer',
    '&:hover': {
      'backgroundColor': 'var(--alt-muted)',
    }
  },
  '.altus-accordion-content': {
    'padding': '0 1.5rem 1.5rem',
    'fontSize': '0.875rem',
    'color': 'var(--alt-fg)',
    'opacity': '0.7',
    'lineHeight': '1.6',
  },
  '.altus-tooltip': {
    'position': 'absolute',
    'zIndex': '50',
    'padding': '0.5rem 0.75rem',
    'fontSize': '10px',
    'fontWeight': '700',
    'textTransform': 'uppercase',
    'letterSpacing': '0.15em',
    'backgroundColor': 'var(--alt-fg)',
    'color': 'var(--alt-bg)',
    'borderRadius': '0.25rem',
    'boxShadow': 'var(--alt-shadow)',
    'pointerEvents': 'none',
    'whiteSpace': 'nowrap',
  },
  '.altus-overlay': {
    'position': 'fixed',
    'inset': '0',
    'backgroundColor': 'rgba(0,0,0,0.4)',
    'backdropFilter': 'blur(4px)',
    'zIndex': '100',
  },
  '.altus-modal': {
    'position': 'fixed',
    'top': '50%',
    'left': '50%',
    'transform': 'translate(-50%, -50%)',
    'zIndex': '110',
    'width': '90%',
    'maxWidth': '500px',
    'backgroundColor': 'var(--alt-bg)',
    'borderRadius': 'var(--alt-radius)',
    'border': '1px solid var(--alt-border)',
    'boxShadow': '0 25px 50px -12px rgba(0,0,0,0.25)',
    'padding': '2rem',
  },
  '.altus-toast': {
    'padding': '0.75rem 1rem',
    'backgroundColor': 'var(--alt-fg)',
    'color': 'var(--alt-bg)',
    'borderRadius': 'var(--alt-radius)',
    'boxShadow': 'var(--alt-shadow)',
    'fontSize': '0.875rem',
    'fontWeight': '600',
    'display': 'flex',
    'alignItems': 'center',
    'gap': '0.75rem',
    'pointerEvents': 'auto',
    'border': '1px solid var(--alt-border)',
    'minWidth': '300px',
    'maxWidth': 'calc(100vw - 2rem)',
    'position': 'relative',
    'overflow': 'hidden',
    '@media (max-width: 640px)': {
      'minWidth': 'calc(100vw - 3rem)',
    }
  },
  '.altus-toast-close': {
    'marginLeft': 'auto',
    'display': 'inline-flex',
    'alignItems': 'center',
    'justifyContent': 'center',
    'width': '1.5rem',
    'height': '1.5rem',
    'borderRadius': '0.25rem',
    'cursor': 'pointer',
    'opacity': '0.5',
    'transition': 'all 0.2s ease',
    'border': 'none',
    'backgroundColor': 'transparent',
    'color': 'inherit',
    '&:hover': {
      'opacity': '1',
      'backgroundColor': 'rgba(0,0,0,0.1)',
    }
  },
  '.altus-toast-success': {
    'backgroundColor': '#ecfdf5',
    'color': '#065f46',
    'borderColor': '#a7f3d0',
  },
  '.altus-toast-error': {
    'backgroundColor': '#fef2f2',
    'color': '#991b1b',
    'borderColor': '#fecaca',
  },
  '.altus-toast-info': {
    'backgroundColor': '#eff6ff',
    'color': '#1e40af',
    'borderColor': '#bfdbfe',
  },
  '.altus-toast-container': {
    'position': 'fixed',
    'zIndex': '250',
    'display': 'flex',
    'flexDirection': 'column',
    'gap': '0.5rem',
    'pointerEvents': 'none',
    'padding': '1rem',
    'width': '100%',
    'maxWidth': 'max-content',
    'alignItems': 'center',
    '@media (max-width: 640px)': {
      'left': '0 !important',
      'right': '0 !important',
      'width': '100% !important',
      'maxWidth': '100% !important',
      'transform': 'none !important',
      'padding': '1rem',
      'alignItems': 'center',
    }
  },
  '.altus-toast-container.top-center': {
    'top': '0',
    'left': '50%',
    'transform': 'translateX(-50%)',
  },
  '.altus-toast-container.bottom-center': {
    'bottom': '0',
    'left': '50%',
    'transform': 'translateX(-50%)',
  },
  '.altus-toast-container.bottom-right': {
    'bottom': '0',
    'right': '0',
    'alignItems': 'flex-end',
  },
  '.altus-nav-overlay': {
    'position': 'fixed',
    'inset': '0',
    'backgroundColor': 'var(--alt-bg)',
    'zIndex': '200',
    'padding': '6rem 2rem 2rem',
    'display': 'flex',
    'flexDirection': 'column',
  },
  '.altus-nav-link': {
    'fontSize': '2.5rem',
    'fontWeight': '900',
    'textTransform': 'uppercase',
    'letterSpacing': '-0.02em',
    'color': 'var(--alt-fg)',
    'transition': 'all 0.3s ease',
    'display': 'block',
    'borderBottom': '1px solid transparent',
    'width': 'fit-content',
    '&:hover': {
      'letterSpacing': '0.05em',
      'color': 'var(--alt-primary)',
    }
  },
  '.altus-logo': {
    'height': '1.5rem',
    'width': 'auto',
    'filter': 'none',
    'transition': 'filter 0.3s ease',
  },
  '[data-theme="navy"] .altus-logo, [data-theme="obsidian"] .altus-logo, [data-theme="mocha"] .altus-logo': {
    'filter': 'invert(1)',
  },
  '.altus-slider': {
    'display': 'flex',
    'overflowX': 'auto',
    'scrollSnapType': 'x mandatory',
    'scrollbarWidth': 'none',
    '&::-webkit-scrollbar': { 'display': 'none' },
    'gap': '1.5rem',
    'padding': '1rem 0',
  },
  '.altus-slider-item': {
    'flex': '0 0 auto',
    'width': '85%',
    'scrollSnapAlign': 'center',
    'transition': 'transform 0.3s ease',
    '&:active': {
      'transform': 'scale(0.98)',
    }
  },
};
